### ISSUE TITLE
Install Instructions don't work

### ISSUE THREAD

**Issue by andybak** [UCL-VR/ubiq-genie#1]
Step 2: "Open a terminal in the Genie folder and run npm install to install the dependencies."

What Genie folder? The root doesn't have a package.json so I tried \Server instead.

However - I get the following warnings and errors: 

	npm warn deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
	npm warn tarball tarball data for ubiq@https://gitpkg.now.sh/UCL-VR/ubiq/Node?176b628c1af34aedad19a35ed5bf4c5a8473953e (sha512-QRrF/zqQ2Ln8Zwg7VD+w/fKcwsD7aHVWF3/CAzt7eeLYj8q7/WEaXuDzxquOW7PHWVbnPNe5DxIafdk0s1Z/Ew==) seems to be corrupted. Trying again.
	npm error code EINTEGRITY
	npm error sha512-QRrF/zqQ2Ln8Zwg7VD+w/fKcwsD7aHVWF3/CAzt7eeLYj8q7/WEaXuDzxquOW7PHWVbnPNe5DxIafdk0s1Z/Ew== integrity checksum failed when using sha512: wanted sha512-QRrF/zqQ2Ln8Zwg7VD+w/fKcwsD7aHVWF3/CAzt7eeLYj8q7/WEaXuDzxquOW7PHWVbnPNe5DxIafdk0s1Z/Ew== but got sha512-5cZGZiV3lfgML03ThX8Xld0qvVXwq+On5DPSBkJR5Pkau0DqIO6rOeMFn9RK/u0I8WS7OoTh1AkG7ifVIge5aA==. (50385 bytes)

Windows 11 and node v20.9.0

**Comment by andybak** [comment]
Tried deleting package-lock.json. Got a different error:

    npm error EISDIR: illegal operation on a directory, symlink 'I:\Unity Projects\ubiq-genie\Server\node_modules\ubiq\modules' -> 'I:\Unity Projects\ubiq-genie\Server\node_modules\modules'
    
EDIT - just realised I'm storing this on an external exFAT drive which is probably the issue with symlinking. I share my project drive between Mac and Windows - hence the avoidance of NTFS. 

    npm install --no-bin-links
    
didn't help so I guess i'll try moving the project.

This one is on me. The original issues with the folder names and package-lock.json is probably going to affect other people however.

EDIT2 - the docs are wrong about the Python steps also. But even when I solved that I get pip errors about torch. ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu116 

I'm giving up for now but happy to help debug if someone picks this up.

**Comment by nsalminen** [comment]
Hi @andybak, thank you for flagging and debugging this! I fixed the outdated information in the README and added some clarifications. I couldn't consistently reproduce the issue you encountered regarding the npm installation, but I did come across it on a specific machine. I updated the package-lock.json, which seems to have addressed this.

The way to install PyTorch will differ depending on the platform, CUDA version, and package manager, so I updated the README to link to the [PyTorch installation instructions](https://pytorch.org/get-started/previous-versions/#v1131) instead. I hope that helps! Please let me know if you face any further issues with installation! 

Lastly, just so you know, Ubiq-Genie will be upgraded to support the latest versions of Ubiq in the coming months and is currently using an older version of Ubiq (0.4.2). New Ubiq features such as the improved WebRTC backend and WebXR support will become available at that point and development should become a bit easier. This will be tracked in #2.
